{% set name = "gspread" %}
{% set version = "3.0.0" %}
{% set sha256 = "8ec04e710bb95e93077612103cd48473faafc10f2f3080dc8a33197989cbf318" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests

test:
  imports:
    - gspread

about:
  home: https://github.com/burnash/gspread
  license: MIT
  license_file: LICENSE.txt
  summary: 'Google Spreadsheets Python API'
  license_family: MIT
  dev_url: https://github.com/burnash/gspread
  doc_url: http://gspread.readthedocs.io/

extra:
  recipe-maintainers:
    - hadim
